/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var LetsGo:String = "event:/Music/LetsGo";
}

class FmodSFX {
    public static inline var DoorOpen:String = "event:/SFX/Door/DoorOpen";
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
    public static inline var FootstepGrass:String = "event:/SFX/Player/FootstepGrass";
    public static inline var FootstepStone:String = "event:/SFX/Player/FootstepStone";
    public static inline var FootstepWood:String = "event:/SFX/Player/FootstepWood";
}
