/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var Awaken:String = "event:/Music/Awaken";
    public static inline var AwakenDanger:String = "event:/Music/AwakenDanger";
    public static inline var AwakenLullaby:String = "event:/Music/AwakenLullaby";
    public static inline var AwakenLullabyEnding:String = "event:/Music/AwakenLullabyEnding";
    public static inline var AwakenSofterC:String = "event:/Music/AwakenSofterC";
    public static inline var Battle:String = "event:/Music/Battle";
    public static inline var BattleWithAlarm:String = "event:/Music/BattleWithAlarm";
    public static inline var BeforeTheEnd:String = "event:/Music/BeforeTheEnd";
    public static inline var Haunted:String = "event:/Music/Haunted";
    public static inline var LetsGo:String = "event:/Music/LetsGo";
    public static inline var Lonk:String = "event:/Music/Lonk";
    public static inline var Silence:String = "event:/Music/Silence";
}

class FmodSFX {
    public static inline var AlarmBreak:String = "event:/SFX/Alarm/AlarmBreak";
    public static inline var AlarmClick:String = "event:/SFX/Alarm/AlarmClick";
    public static inline var AlarmClock:String = "event:/SFX/Alarm/AlarmClock";
    public static inline var AlarmClockHit:String = "event:/SFX/Alarm/AlarmClockHit";
    public static inline var AlarmSwing:String = "event:/SFX/Alarm/AlarmSwing";
    public static inline var BattleStart:String = "event:/SFX/Battle/BattleStart";
    public static inline var ChestBattleOpen:String = "event:/SFX/Chest/ChestBattleOpen";
    public static inline var ChestBattleOpen2:String = "event:/SFX/Chest/ChestBattleOpen2";
    public static inline var ChestBattleOpen3:String = "event:/SFX/Chest/ChestBattleOpen3";
    public static inline var ChestBattleOpen4:String = "event:/SFX/Chest/ChestBattleOpen4";
    public static inline var ChestBattleOpenInitialImpact:String = "event:/SFX/Chest/ChestBattleOpenInitialImpact";
    public static inline var ChestOpen:String = "event:/SFX/Chest/ChestOpen";
    public static inline var ChestOpenSimple:String = "event:/SFX/Chest/ChestOpenSimple";
    public static inline var CluddSnore:String = "event:/SFX/Cludd/CluddSnore";
    public static inline var CompassBreak:String = "event:/SFX/Compass/CompassBreak";
    public static inline var DoorClose:String = "event:/SFX/Door/DoorClose";
    public static inline var DoorOpen:String = "event:/SFX/Door/DoorOpen";
    public static inline var PotDestroy:String = "event:/SFX/Enemies/Pot/PotDestroy";
    public static inline var PotPlayerAttemptStrike:String = "event:/SFX/Enemies/Pot/PotPlayerAttemptStrike";
    public static inline var PotPlayerCursorSpawn:String = "event:/SFX/Enemies/Pot/PotPlayerCursorSpawn";
    public static inline var PotPlayerCursorSpawn2:String = "event:/SFX/Enemies/Pot/PotPlayerCursorSpawn2";
    public static inline var PotPlayerCursorSpawn3:String = "event:/SFX/Enemies/Pot/PotPlayerCursorSpawn3";
    public static inline var PotPlayerStrikeFinal:String = "event:/SFX/Enemies/Pot/PotPlayerStrikeFinal";
    public static inline var PotRebound:String = "event:/SFX/Enemies/Pot/PotRebound";
    public static inline var PotRebound2:String = "event:/SFX/Enemies/Pot/PotRebound2";
    public static inline var PotRebound3:String = "event:/SFX/Enemies/Pot/PotRebound3";
    public static inline var PotRingSpawn:String = "event:/SFX/Enemies/Pot/PotRingSpawn";
    public static inline var PotTargetSpawn:String = "event:/SFX/Enemies/Pot/PotTargetSpawn";
    public static inline var GateOpen:String = "event:/SFX/Gate/GateOpen";
    public static inline var LonkFinalHit:String = "event:/SFX/Lonk/LonkFinalHit";
    public static inline var LonkLaugh:String = "event:/SFX/Lonk/LonkLaugh";
    public static inline var LonkLaugh2:String = "event:/SFX/Lonk/LonkLaugh2";
    public static inline var LonkLaugh3:String = "event:/SFX/Lonk/LonkLaugh3";
    public static inline var Undertone:String = "event:/SFX/Lonk/Undertone";
    public static inline var LonkHouseCollapse:String = "event:/SFX/LonkHouse/LonkHouseCollapse";
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
    public static inline var PadlockDown:String = "event:/SFX/Padlock/PadlockDown";
    public static inline var PadlockDown2:String = "event:/SFX/Padlock/PadlockDown2";
    public static inline var PadlockFailDown:String = "event:/SFX/Padlock/PadlockFailDown";
    public static inline var PadlockFailTone:String = "event:/SFX/Padlock/PadlockFailTone";
    public static inline var PadlockFailUp:String = "event:/SFX/Padlock/PadlockFailUp";
    public static inline var PadlockSelect:String = "event:/SFX/Padlock/PadlockSelect";
    public static inline var PadlockSuccessMetal:String = "event:/SFX/Padlock/PadlockSuccessMetal";
    public static inline var PadlockSuccessMetal2:String = "event:/SFX/Padlock/PadlockSuccessMetal2";
    public static inline var PadlockSuccessMetal3:String = "event:/SFX/Padlock/PadlockSuccessMetal3";
    public static inline var PadlockSuccessMetal4:String = "event:/SFX/Padlock/PadlockSuccessMetal4";
    public static inline var PadlockSuccessTone:String = "event:/SFX/Padlock/PadlockSuccessTone";
    public static inline var PadlockUp:String = "event:/SFX/Padlock/PadlockUp";
    public static inline var PadlockUp2:String = "event:/SFX/Padlock/PadlockUp2";
    public static inline var FootstepDirt:String = "event:/SFX/Player/FootstepDirt";
    public static inline var FootstepGrass:String = "event:/SFX/Player/FootstepGrass";
    public static inline var FootstepGrassReal:String = "event:/SFX/Player/FootstepGrassReal";
    public static inline var FootstepStone:String = "event:/SFX/Player/FootstepStone";
    public static inline var FootstepWood:String = "event:/SFX/Player/FootstepWood";
    public static inline var StairsDown:String = "event:/SFX/Player/StairsDown";
    public static inline var StairsUp:String = "event:/SFX/Player/StairsUp";
    public static inline var PotExplode:String = "event:/SFX/Pot/PotExplode";
    public static inline var PotTick1:String = "event:/SFX/Pot/PotTick1";
    public static inline var PotTick2:String = "event:/SFX/Pot/PotTick2";
    public static inline var PotTick3:String = "event:/SFX/Pot/PotTick3";
    public static inline var PotTick4:String = "event:/SFX/Pot/PotTick4";
    public static inline var PotTick5:String = "event:/SFX/Pot/PotTick5";
    public static inline var Typewriter:String = "event:/SFX/Typewriter/Typewriter";
    public static inline var TypeWriterSingleStroke:String = "event:/SFX/Typewriter/TypeWriterSingleStroke";
    public static inline var WorldCollectImportant:String = "event:/SFX/World/WorldCollectImportant";
    public static inline var WorldCollectImportantDelay:String = "event:/SFX/World/WorldCollectImportantDelay";
}
